language: php
php:
  - '7.1'

before_script:
  - composer self-update
  - nvm install lts/*
  - npm i -g gulp

install:
  - composer install --prefer-dist --no-dev --no-interaction
  - npm i
  - gulp

script:
  echo ''